#! /usr/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

startdir=$(pwd)
tmpfile=$(mktemp)

if [[ $1 = '--latest' ]]; then
	makepkg -od 2&> /dev/null
fi

source /etc/makepkg.conf
source PKGBUILD

pkgbase=${pkgbase:-${pkgname[0]}}

if [[ $BUILDDIR = $startdir ]]; then
	srcdir="$BUILDDIR/src"
else
	srcdir="$BUILDDIR/$pkgbase/src"
fi

if [[ "`type -t pkgver`" = 'function' ]]; then
	cd $srcdir
	pkgver 2> $tmpfile 1> /dev/null

	if [[ -s $tmpfile ]]; then
		echo "?"
	else
		cd $srcdir
		ver=$(pkgver)
		echo $ver-$pkgrel
	fi
else
	echo $pkgver-$pkgrel
fi
