#! /bin/bash

startdir=$(pwd)
tmpfile=$(mktemp)

if [[ $1 = '--latest' ]]; then
	makepkg -od 2&> /dev/null
fi

source /etc/makepkg.conf
source PKGBUILD

pkgbase=${pkgbase:-${pkgname[0]}}

if [[ $BUILDDIR = $startdir ]]; then
	srcdir="$BUILDDIR/src"
else
	srcdir="$BUILDDIR/$pkgbase/src"
fi

if [[ "`type -t pkgver`" = 'function' ]]; then
	cd $srcdir
	pkgver 2> $tmpfile 1> /dev/null

	if [[ -s $tmpfile ]]; then
		echo "?"
	else
		cd $srcdir
		ver=$(pkgver)
		echo $ver-$pkgrel
	fi
else
	echo $pkgver-$pkgrel
fi