#!/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -x

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

os_name=$1
url=$2
ostree_dir=$3
branch=$4
image_path='papyros.img'
final_image_path=$5
size=$6
arch=$7

#----- Utility methods -----#

die() {
    echo "$@"
    exit 1
}

replace() {
    sed s#"$1"#"$2"# < $3 > tmpfile && mv tmpfile $3
}

# Require that the command be run as root (via sudo)
(( EUID != 0 )) && die "This script must be run as root."

sysroot=/mnt/${os_name}_$arch

if [ $arch == x86_64 ]; then
	loop=/dev/loop8
else
	loop=/dev/loop9
fi

# Make sure the loop device is ready for use
umount $loop || true # Ignore the return value
losetup -d $loop || true # Ignore the return value

rm -f "$image_path"

sudo -u buildbot truncate -s $size "$image_path"

parted "$image_path" mklabel msdos
parted "$image_path" mkpart primary ext4 0% 100%
parted "$image_path" set 1 boot on

losetup $loop "$image_path" -o 1048576

mkfs.ext4 $loop

e2label $loop $os_name

mkdir -p "$sysroot"

mount $loop "$sysroot"

$DIR/ostree-install -n $os_name -o "$ostree_dir" -u "$url" -b $branch "$sysroot"

sed -i 's/KERNEL \//KERNEL \/boot\//g' "$sysroot"/boot/syslinux/syslinux.cfg
sed -i 's/INITRD \//INITRD \/boot\//g' "$sysroot"/boot/syslinux/syslinux.cfg

tree -L 3 "$sysroot"
less "$sysroot"/boot/syslinux/syslinux.cfg

umount $sysroot

losetup -d $loop

dd bs=440 count=1 conv=notrunc \
    if=/usr/lib/syslinux/bios/mbr.bin of="$image_path"

rm -f "$image_path".xz
xz "$image_path"

mv "$image_path.xz" "$final_image_path.xz"

chmod -R a+r "$final_image_path".xz
chown -R buildbot:buildbot "$final_image_path".xz
