#!/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -x

arch=$1
os_dir=$2

kernel_version=$(pacman -r "$os_dir" -Q linux | cut -d' ' -f 2)-ARCH

linux$arch systemd-nspawn -D "$os_dir" \
    mkinitcpio -c /etc/ostree-mkinitcpio.conf -g /boot/initramfs-linux.img \
        -k $kernel_version -S autodetect

boot_dir="$os_dir"/boot

rm -f "$boot_dir"/initramfs-linux-fallback.img

checksum=$(cat "$boot_dir"/initramfs-* "$boot_dir"/vmlinuz-* | \
           sha256sum | cut -d' ' -f 1)

mv "$boot_dir"/initramfs-*.img "$boot_dir"/initramfs-$checksum
mv "$boot_dir"/vmlinuz-* "$boot_dir"/vmlinuz-$checksum