#!/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
set -x

os_dir=$1

rm "$os_dir"/etc/pacman.d/gnupg/S.gpg-agent

mkdir -p "$os_dir"/usr/etc/
mkdir "$os_dir"/sysroot
rmdir "$os_dir"/{home,opt,root,mnt}
rm -rf "$os_dir"/srv
rsync -av "$os_dir"/etc "$os_dir"/usr/etc/
rm -rf "$os_dir"/etc

ln -s sysroot/ostree "$os_dir"/ostree
ln -s sysroot/tmp "$os_dir"/tmp
ln -s var/home "$os_dir"/home
ln -s var/roothome "$os_dir"/root

chmod a+rX "$os_dir"/{bin,boot,lib,sysroot,usr,var}

cat << EOF > "$os_dir"/usr/etc/fstab
LABEL=$OSNAME-boot /boot ext4 rw,relatime,data=ordered 0 2
LABEL=$OSNAME-root / ext4 rw,relatime,data=ordered 0 1
EOF

cat << EOF > "$os_dir"/usr/lib/tmpfiles.d/ostree.conf
d /var/log/journal 0755 root root -
L /var/home - - - - ../sysroot/home
d /var/roothome 0700 root root -
d /var/lib 0755 root root -
EOF