#!/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

arch=$1
channel_dir=$2
os_dir=$3

mkdir -p "$os_dir"/etc

# Set up the os-release file
cp "$channel_dir"/os-release "$os_dir"/etc/os-release

# Copy the post-install setup file and run it
cp "$channel_dir"/post-install "$os_dir"/post-install
chmod +x "$os_dir"/post-install

systemd-nspawn -D "$os_dir" /post-install

rm "$os_dir"/post-install