#!/bin/bash
#
# Archbuild - Buildbot configuration for Papyros
#
# Copyright (C) 2015 Michael Spencer <sonrisesoftware@gmail.com>
# Copyright (C) 2015 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

usage() {
    echo "Usage: $0 [-l] <path to PKGBUILD>"
    exit 1
}

while getopts "l" o; do
    case "${o}" in
        l)
            makepkg -od &>/dev/null
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

pkgbuild=$1
prev_ver=$2

if [ -z "$pkgbuild" ]; then
    usage
fi

source $pkgbuild

basedir=`readlink -f $(dirname $pkgbuild)`
srcdir="$basedir/src"

pkgbase=${pkgbase:-${pkgname[0]}}
if [ "`type -t changelog`" = 'function' ]; then
    cd $srcdir
    changelog $prev_ver
else
    if [ "`type -t pkgver`" = 'function' ]; then
        cd $srcdir
        pkgver=$(pkgver)

        if [ -z "$pkgver" ]; then
            pkgver="?"
        fi
    fi
    
    if [[ $prev_ver != $pkgver ]]; then
        echo Update $prev_ver -> $pkgver
    fi
fi

rm -rf $srcdir